### ISSUE TITLE
[CRASH] Segfaults when opening Speed/Duration dialogue

### ISSUE THREAD

**Issue by DaniSeeh** [sobotka/olive#14]
Segfault report
Build: 840b412
Reproducible: Yes
Steps to Reproduce:
Run Olive and set OCIO config to nuke-default (I used sRGB colorspace since all my assets are sRGB)
New Sequence set at 3840x2160 60 fps
Import PNG
Drag to timeline (it also is defaulting to 0 frames at the moment, which is another bug but not this crash)
Expand image to one frame in timeline
Right click on Footage in Timeline
Left click Speed/Duration
Segfault
System Details:
Manjaro Gnome (latest)
AMD Ryzen 1700x
NVIDIA GTX 1070
32gb RAM

```
Segmentation fault (core dumped)
[daniel@daniel-pc app]$ gdb ./olive-editor
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./olive-editor...
(No debugging symbols found in ./olive-editor)
(gdb) run
Starting program: /home/daniel/Downloads/olive-840b41256a98a3982e370c67f50ab4a91e9bf81b/app/olive-editor 
/usr/lib/../share/gcc-9.2.0/python/libstdcxx/v6/xmethods.py:731: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  refcounts = ['_M_refcount']['_M_pi']
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffea731700 (LWP 4208)]
qt5ct: using qt5ct plugin
[Detaching after fork from child process 4209]
[Detaching after fork from child process 4210]
Using Qt version: 5.14.0
[DEBUG] CONFIG: This is a 0.1.x config file, upconvert ((null):0)
[DEBUG]   CONFIG: Finding closest match to "29.97" ((null):0)
[DEBUG]   CONFIG: Closest match was 29.97 ((null):0)
[New Thread 0x7fffe8ee8700 (LWP 4213)]
[New Thread 0x7fffe232a700 (LWP 4214)]
[New Thread 0x7fffe1b29700 (LWP 4215)]
[New Thread 0x7fffe1328700 (LWP 4216)]
[New Thread 0x7fffe0b27700 (LWP 4217)]
[New Thread 0x7fffd3fff700 (LWP 4218)]
[New Thread 0x7fffd37fe700 (LWP 4219)]
[New Thread 0x7fffd2ffd700 (LWP 4220)]
[New Thread 0x7fffd27fc700 (LWP 4221)]
[New Thread 0x7fffd1ffb700 (LWP 4222)]
[New Thread 0x7fffd17fa700 (LWP 4223)]
[New Thread 0x7fffd0ff9700 (LWP 4224)]
[New Thread 0x7fffaffff700 (LWP 4225)]
[New Thread 0x7fffaf7fe700 (LWP 4226)]
[New Thread 0x7fffaeffd700 (LWP 4227)]
[New Thread 0x7fffae7fc700 (LWP 4228)]
[New Thread 0x7fffadffb700 (LWP 4229)]
[New Thread 0x7fffad7fa700 (LWP 4230)]
[DEBUG] D-Bus global menu: no ((null):0)
[DEBUG] palette support is disabled ((null):0)
[DEBUG] custom style sheet is disabled ((null):0)
[New Thread 0x7fff8ffff700 (LWP 4231)]
[INFO] Setting output audio device to "alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo" ((null):0)
[WARNING] Invalid params found: 0 0 -1 ((null):0)
[Thread 0x7fffe8ee8700 (LWP 4213) exited]
[New Thread 0x7fffe8ee8700 (LWP 4233)]
[Thread 0x7fffe8ee8700 (LWP 4233) exited]
[New Thread 0x7fffe8ee8700 (LWP 4234)]
[Thread 0x7fffe8ee8700 (LWP 4234) exited]
[WARNING] Invalid params found: 0 0 -1 ((null):0)
[DEBUG] OpenGLBackend(0x5555558af5d0) is waiting for 0 busy workers ((null):0)
[DEBUG] Cache invalidated between 0 and 0 ((null):0)
[New Thread 0x7fffe8ee8700 (LWP 4235)]
[New Thread 0x7fff8e82b700 (LWP 4236)]
[New Thread 0x7fff8e02a700 (LWP 4237)]
[New Thread 0x7fff8d829700 (LWP 4238)]
[New Thread 0x7fff8d028700 (LWP 4239)]
[New Thread 0x7fff8c827700 (LWP 4240)]
[New Thread 0x7fff5ffff700 (LWP 4241)]
[New Thread 0x7fff67fff700 (LWP 4242)]
[New Thread 0x7fff677fe700 (LWP 4243)]
[New Thread 0x7fff66ffd700 (LWP 4244)]
[New Thread 0x7fff667fc700 (LWP 4245)]
[New Thread 0x7fff65ffb700 (LWP 4246)]
[New Thread 0x7fff657fa700 (LWP 4247)]
[New Thread 0x7fff64ff9700 (LWP 4248)]
[New Thread 0x7fff5f7fe700 (LWP 4249)]
[New Thread 0x7fff27fd7700 (LWP 4251)]
[New Thread 0x7fff26811700 (LWP 4252)]
[New Thread 0x7fff26010700 (LWP 4253)]
[New Thread 0x7fff2580f700 (LWP 4254)]
[New Thread 0x7fff2500e700 (LWP 4255)]
[New Thread 0x7fff2480d700 (LWP 4256)]
[New Thread 0x7fff1ffff700 (LWP 4257)]
[New Thread 0x7fff1f7fe700 (LWP 4258)]
[New Thread 0x7fff1effd700 (LWP 4259)]
[New Thread 0x7fff1e7fc700 (LWP 4260)]
[New Thread 0x7fff1dffb700 (LWP 4261)]
[New Thread 0x7fff1d7fa700 (LWP 4262)]
[New Thread 0x7fff1cff9700 (LWP 4263)]
[New Thread 0x7fff1c7f8700 (LWP 4264)]
[New Thread 0x7fff1bff7700 (LWP 4265)]
[New Thread 0x7fff1b7f6700 (LWP 4266)]
[New Thread 0x7fff1aff5700 (LWP 4267)]
[Thread 0x7fff26811700 (LWP 4252) exited]
[Thread 0x7fff26010700 (LWP 4253) exited]
[Thread 0x7fff2580f700 (LWP 4254) exited]
[Thread 0x7fff2500e700 (LWP 4255) exited]
[Thread 0x7fff2480d700 (LWP 4256) exited]
[Thread 0x7fff1ffff700 (LWP 4257) exited]
[Thread 0x7fff1f7fe700 (LWP 4258) exited]
[Thread 0x7fff1effd700 (LWP 4259) exited]
[Thread 0x7fff1e7fc700 (LWP 4260) exited]
[Thread 0x7fff1dffb700 (LWP 4261) exited]
[Thread 0x7fff1d7fa700 (LWP 4262) exited]
[Thread 0x7fff1c7f8700 (LWP 4264) exited]
[Thread 0x7fff1cff9700 (LWP 4263) exited]
[Thread 0x7fff1bff7700 (LWP 4265) exited]
[Thread 0x7fff1aff5700 (LWP 4267) exited]
[Thread 0x7fff1b7f6700 (LWP 4266) exited]
[Thread 0x7fff27fd7700 (LWP 4251) exited]
[New Thread 0x7fff27fd7700 (LWP 4268)]
[New Thread 0x7fff1aff5700 (LWP 4269)]
[New Thread 0x7fff1b7f6700 (LWP 4270)]
[New Thread 0x7fff1bff7700 (LWP 4271)]
[New Thread 0x7fff277d6700 (LWP 4272)]
[New Thread 0x7fff26fd5700 (LWP 4273)]
[New Thread 0x7fff267d4700 (LWP 4274)]
[New Thread 0x7fff25fd3700 (LWP 4275)]
[New Thread 0x7fff257d2700 (LWP 4276)]
[New Thread 0x7fff24fd1700 (LWP 4277)]
[New Thread 0x7fff1ffff700 (LWP 4278)]
[New Thread 0x7fff1f7fe700 (LWP 4279)]
[New Thread 0x7fff1effd700 (LWP 4280)]
[New Thread 0x7fff1e7fc700 (LWP 4281)]
[New Thread 0x7fff1dffb700 (LWP 4282)]
[New Thread 0x7fff1d7fa700 (LWP 4283)]
[Thread 0x7fff27fd7700 (LWP 4268) exited]
[Thread 0x7fff1aff5700 (LWP 4269) exited]
[Thread 0x7fff1bff7700 (LWP 4271) exited]
[Thread 0x7fff277d6700 (LWP 4272) exited]
[Thread 0x7fff1b7f6700 (LWP 4270) exited]
[Thread 0x7fff26fd5700 (LWP 4273) exited]
[Thread 0x7fff267d4700 (LWP 4274) exited]
[Thread 0x7fff25fd3700 (LWP 4275) exited]
[Thread 0x7fff257d2700 (LWP 4276) exited]
[Thread 0x7fff24fd1700 (LWP 4277) exited]
[Thread 0x7fff1ffff700 (LWP 4278) exited]
[Thread 0x7fff1f7fe700 (LWP 4279) exited]
[Thread 0x7fff1effd700 (LWP 4280) exited]
[Thread 0x7fff1e7fc700 (LWP 4281) exited]
[Thread 0x7fff1dffb700 (LWP 4282) exited]
[Thread 0x7fff1d7fa700 (LWP 4283) exited]
[New Thread 0x7fff1d7fa700 (LWP 4284)]
[New Thread 0x7fff1dffb700 (LWP 4285)]
[New Thread 0x7fff1e7fc700 (LWP 4286)]
[New Thread 0x7fff1effd700 (LWP 4287)]
[New Thread 0x7fff27fd7700 (LWP 4288)]
[New Thread 0x7fff277d6700 (LWP 4289)]
[New Thread 0x7fff26fd5700 (LWP 4290)]
[New Thread 0x7fff267d4700 (LWP 4291)]
[New Thread 0x7fff25fd3700 (LWP 4292)]
[New Thread 0x7fff257d2700 (LWP 4293)]
[New Thread 0x7fff24fd1700 (LWP 4294)]
[New Thread 0x7fff1ffff700 (LWP 4295)]
[New Thread 0x7fff1f7fe700 (LWP 4296)]
[New Thread 0x7fff1cff9700 (LWP 4297)]
[New Thread 0x7fff1c7f8700 (LWP 4298)]
[New Thread 0x7fff1bff7700 (LWP 4299)]
[New Thread 0x7fff1b7f6700 (LWP 4300)]
[Thread 0x7fff1dffb700 (LWP 4285) exited]
[Thread 0x7fff1e7fc700 (LWP 4286) exited]
[Thread 0x7fff1effd700 (LWP 4287) exited]
[Thread 0x7fff27fd7700 (LWP 4288) exited]
[Thread 0x7fff277d6700 (LWP 4289) exited]
[Thread 0x7fff26fd5700 (LWP 4290) exited]
[Thread 0x7fff267d4700 (LWP 4291) exited]
[Thread 0x7fff25fd3700 (LWP 4292) exited]
[Thread 0x7fff257d2700 (LWP 4293) exited]
[Thread 0x7fff24fd1700 (LWP 4294) exited]
[Thread 0x7fff1ffff700 (LWP 4295) exited]
[Thread 0x7fff1f7fe700 (LWP 4296) exited]
[Thread 0x7fff1cff9700 (LWP 4297) exited]
[Thread 0x7fff1c7f8700 (LWP 4298) exited]
[Thread 0x7fff1bff7700 (LWP 4299) exited]
[Thread 0x7fff1b7f6700 (LWP 4300) exited]
[Thread 0x7fff1d7fa700 (LWP 4284) exited]
[New Thread 0x7fff1d7fa700 (LWP 4301)]
[New Thread 0x7fff1b7f6700 (LWP 4302)]
[New Thread 0x7fff1bff7700 (LWP 4303)]
[New Thread 0x7fff1c7f8700 (LWP 4304)]
[New Thread 0x7fff27fd7700 (LWP 4305)]
[New Thread 0x7fff277d6700 (LWP 4306)]
[New Thread 0x7fff26fd5700 (LWP 4307)]
[New Thread 0x7fff267d4700 (LWP 4308)]
[New Thread 0x7fff25fd3700 (LWP 4309)]
[New Thread 0x7fff257d2700 (LWP 4310)]
[New Thread 0x7fff24fd1700 (LWP 4311)]
[New Thread 0x7fff1ffff700 (LWP 4312)]
[New Thread 0x7fff1f7fe700 (LWP 4313)]
[New Thread 0x7fff1effd700 (LWP 4314)]
[New Thread 0x7fff1e7fc700 (LWP 4315)]
[New Thread 0x7fff1dffb700 (LWP 4316)]
[Thread 0x7fff1d7fa700 (LWP 4301) exited]
[Thread 0x7fff1b7f6700 (LWP 4302) exited]
[Thread 0x7fff1bff7700 (LWP 4303) exited]
[Thread 0x7fff1c7f8700 (LWP 4304) exited]
[Thread 0x7fff27fd7700 (LWP 4305) exited]
[Thread 0x7fff277d6700 (LWP 4306) exited]
[Thread 0x7fff26fd5700 (LWP 4307) exited]
[Thread 0x7fff25fd3700 (LWP 4309) exited]
[Thread 0x7fff267d4700 (LWP 4308) exited]
[Thread 0x7fff257d2700 (LWP 4310) exited]
[Thread 0x7fff24fd1700 (LWP 4311) exited]
[Thread 0x7fff1ffff700 (LWP 4312) exited]
[Thread 0x7fff1f7fe700 (LWP 4313) exited]
[Thread 0x7fff1effd700 (LWP 4314) exited]
[Thread 0x7fff1e7fc700 (LWP 4315) exited]
[Thread 0x7fff1dffb700 (LWP 4316) exited]
[DEBUG] Cache invalidated between 0 and 0.683333 ((null):0)
[DEBUG] Cache invalidated between 0.683333 and 0.683333 ((null):0)
Thread 1 "olive-editor" received signal SIGSEGV, Segmentation fault.
0x000055555562e6fc in Block::speed() const ()
(gdb) bt
#0  0x000055555562e6fc in Block::speed() const ()
#1  0x000055555562680b in SpeedDurationDialog::SpeedDurationDialog(rational const&, QList<ClipBlock*> const&, QWidget*) ()
#2  0x00005555556f448f in TimelineWidget::ShowSpeedDurationDialog() ()
#3  0x00007ffff42f23f0 in ?? () from /usr/lib/libQt5Core.so.5
#4  0x00007ffff4d4cf23 in QAction::triggered(bool) () from /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff4d4f60c in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt5Widgets.so.5
#6  0x00007ffff4edcab3 in ?? () from /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff4ee436c in ?? () from /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff4ee53b3 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff4d977e6 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff4ee7a0c in QMenu::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff4d53472 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff4d5ced8 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff42bc8b2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#14 0x00007ffff4d5bff6 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff4db3928 in ?? () from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff4db5f14 in ?? () from /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff4d53472 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff4d5cc89 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff42bc8b2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#20 0x00007ffff46832c4 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /usr/lib/libQt5Gui.so.5
#21 0x00007ffff46849d6 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /usr/lib/libQt5Gui.so.5
#22 0x00007ffff465dc2c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Gui.so.5
#23 0x00007fffeb34ba2c in ?? () from /usr/lib/libQt5XcbQpa.so.5
#24 0x00007fffee8cd39e in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#25 0x00007fffee8cf1b1 in ?? () from /usr/lib/libglib-2.0.so.0
#26 0x00007fffee8cf1f1 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#27 0x00007ffff4314d40 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#28 0x00007ffff42bb41c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#29 0x00007ffff4ee1f53 in QMenu::exec(QPoint const&, QAction*) () from /usr/lib/libQt5Widgets.so.5
#30 0x00005555556f2970 in TimelineWidget::ShowContextMenu() ()
#31 0x00007ffff42f23f0 in ?? () from /usr/lib/libQt5Core.so.5
#32 0x00007ffff4d7c496 in QWidget::customContextMenuRequested(QPoint const&) () from /usr/lib/libQt5Widgets.so.5
#33 0x00007ffff4d984d3 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#34 0x00007ffff4e4922f in QFrame::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#35 0x00007ffff50bc843 in QGraphicsView::viewportEvent(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#36 0x00007ffff42bc5c3 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#37 0x00007ffff4d53461 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#38 0x00007ffff4d5d746 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#39 0x00007ffff42bc8b2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
--Type <RET> for more, q to quit, c to continue without paging--<RET>
#40 0x00007ffff4db357d in ?? () from /usr/lib/libQt5Widgets.so.5
#41 0x00007ffff4db5f14 in ?? () from /usr/lib/libQt5Widgets.so.5
#42 0x00007ffff4d53472 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#43 0x00007ffff4d5cc89 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#44 0x00007ffff42bc8b2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#45 0x00007ffff46832c4 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /usr/lib/libQt5Gui.so.5
#46 0x00007ffff46849d6 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /usr/lib/libQt5Gui.so.5
#47 0x00007ffff465dc2c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Gui.so.5
#48 0x00007fffeb34ba2c in ?? () from /usr/lib/libQt5XcbQpa.so.5
#49 0x00007fffee8cd39e in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#50 0x00007fffee8cf1b1 in ?? () from /usr/lib/libglib-2.0.so.0
#51 0x00007fffee8cf1f1 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#52 0x00007ffff4314d40 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#53 0x00007ffff42bb41c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#54 0x00007ffff42c3426 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#55 0x00005555555c7bc3 in main ()
(gdb) <RET>
Undefined command: "<RET>".  Try "help".
(gdb) 
```

**Comment by DaniSeeh** [comment]
@itsmattkc fixed in ce17d94
