### ISSUE TITLE
[CRASH] Crash when opening sequence after loading project file

### ISSUE THREAD

**Issue by DaniSeeh** [sobotka/olive#22]
**Platform**
Manjaro Gnome
AMD Ryzen 7 1700x
GTX 1070 8gb
32gb DDR4 RAM
Build: 2fe680d

**Summary**
Save Olive 0.2 project file from same build (2fe680d). Load project file after selecting nuke-default color config file and selecting sRGB as default input color space. File loads, but upon double clicking sequence to open it Olive crashes.

**Additional Information / Output**
```
[daniel@daniel-pc app]$ gdb ./olive-editor
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./olive-editor...
(No debugging symbols found in ./olive-editor)
(gdb) run
Starting program: /home/daniel/Downloads/olive-2fe680dccdebac566ba8c0137c1297101bff55ab/app/olive-editor 
/usr/lib/../share/gcc-9.2.0/python/libstdcxx/v6/xmethods.py:731: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  refcounts = ['_M_refcount']['_M_pi']
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffea715700 (LWP 6081)]
qt5ct: using qt5ct plugin
[Detaching after fork from child process 6082]
[Detaching after fork from child process 6083]
Using Qt version: 5.14.1
[DEBUG] CONFIG: This is a 0.1.x config file, upconvert ((null):0)
[DEBUG]   CONFIG: Finding closest match to "29.97" ((null):0)
[DEBUG]   CONFIG: Closest match was 29.97 ((null):0)
[New Thread 0x7fffe98c0700 (LWP 6086)]
[New Thread 0x7fffe90bf700 (LWP 6087)]
[New Thread 0x7fffe88be700 (LWP 6088)]
[New Thread 0x7fffdbfff700 (LWP 6089)]
[New Thread 0x7fffdb7fe700 (LWP 6090)]
[New Thread 0x7fffdaffd700 (LWP 6091)]
[New Thread 0x7fffda7fc700 (LWP 6092)]
[New Thread 0x7fffd9ffb700 (LWP 6093)]
[New Thread 0x7fffd97fa700 (LWP 6094)]
[New Thread 0x7fffd8ff9700 (LWP 6095)]
[New Thread 0x7fffbbfff700 (LWP 6096)]
[New Thread 0x7fffbb7fe700 (LWP 6097)]
[New Thread 0x7fffbaffd700 (LWP 6098)]
[New Thread 0x7fffba7fc700 (LWP 6099)]
[New Thread 0x7fffb9ffb700 (LWP 6100)]
[New Thread 0x7fffb97fa700 (LWP 6101)]
[New Thread 0x7fffb8ff9700 (LWP 6102)]
[New Thread 0x7fff9bfff700 (LWP 6103)]
[DEBUG] D-Bus global menu: no ((null):0)
[DEBUG] palette support is disabled ((null):0)
[DEBUG] custom style sheet is disabled ((null):0)
[New Thread 0x7fff98da5700 (LWP 6104)]
[INFO] Setting output audio device to "alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo" ((null):0)
[WARNING] Invalid params found: 0 0 -1 ((null):0)
[Thread 0x7fffe98c0700 (LWP 6086) exited]
[New Thread 0x7fffe98c0700 (LWP 6105)]
[WARNING] Empty filename passed to function ((null):0)
[Thread 0x7fffe98c0700 (LWP 6105) exited]
[New Thread 0x7fffe98c0700 (LWP 6109)]
[WARNING] Empty filename passed to function ((null):0)
[Thread 0x7fffe98c0700 (LWP 6109) exited]
[New Thread 0x7fffe98c0700 (LWP 6110)]
[DEBUG] Project version: "0.2.0" ((null):0)
[Thread 0x7fffe98c0700 (LWP 6110) exited]
[WARNING] Invalid params found: 0 0 -1 ((null):0)
[DEBUG] OpenGLBackend(0x5555558d6170) is waiting for 0 busy workers ((null):0)
[DEBUG] Cache invalidated between 0 and 9.03333 ((null):0)
[New Thread 0x7fffe98c0700 (LWP 6111)]
[New Thread 0x7fff7bfff700 (LWP 6112)]
[New Thread 0x7fff7b7fe700 (LWP 6113)]
[New Thread 0x7fff7affd700 (LWP 6114)]
[New Thread 0x7fff7a7fc700 (LWP 6115)]
[New Thread 0x7fff79ffb700 (LWP 6116)]
[New Thread 0x7fff797fa700 (LWP 6117)]
[New Thread 0x7fff78ff9700 (LWP 6118)]
[New Thread 0x7fff63fff700 (LWP 6119)]
[New Thread 0x7fff637fe700 (LWP 6120)]
[New Thread 0x7fff62ffd700 (LWP 6121)]
[New Thread 0x7fff627fc700 (LWP 6122)]
[New Thread 0x7fff61ffb700 (LWP 6123)]
[New Thread 0x7fff617fa700 (LWP 6124)]
[New Thread 0x7fff60ff9700 (LWP 6125)]
[New Thread 0x7fff3ffff700 (LWP 6126)]
[New Thread 0x7fff3f7fe700 (LWP 6127)]
[DEBUG] Cache invalidated between 0 and 9.03333 ((null):0)
[New Thread 0x7fff23248700 (LWP 6128)]
[New Thread 0x7fff22a47700 (LWP 6129)]
[New Thread 0x7fff22246700 (LWP 6130)]
[New Thread 0x7fff21a45700 (LWP 6131)]
[New Thread 0x7fff21244700 (LWP 6132)]
[New Thread 0x7fff20a43700 (LWP 6133)]
[New Thread 0x7fff0bfff700 (LWP 6134)]
[New Thread 0x7fff0b7fe700 (LWP 6135)]
[New Thread 0x7fff0affd700 (LWP 6136)]
[New Thread 0x7fff0a7fc700 (LWP 6137)]
[New Thread 0x7fff09ffb700 (LWP 6138)]
[New Thread 0x7fff097fa700 (LWP 6139)]
[New Thread 0x7fff08ff9700 (LWP 6140)]
[New Thread 0x7ffeebfff700 (LWP 6141)]
[New Thread 0x7ffeeb7fe700 (LWP 6142)]
[New Thread 0x7ffeeaffd700 (LWP 6143)]
[WARNING] Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.
 ((null):0)
terminate called after throwing an instance of 'OpenColorIO::v1::Exception'
  what():  Could not find colorspace '
        '.

Thread 41 "QThread" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff3f7fe700 (LWP 6127)]
0x00007ffff3b3ef25 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff3b3ef25 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff3b28897 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff3ec281d in __gnu_cxx::__verbose_terminate_handler ()
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff3ecf4da in __cxxabiv1::__terminate (handler=<optimized out>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff3ecf537 in std::terminate ()
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007ffff40a3ca1 in qTerminate() () from /usr/lib/libQt5Core.so.5
#6  0x00007ffff40a56fc in ?? () from /usr/lib/libQt5Core.so.5
#7  0x00007ffff37ee4cf in start_thread () from /usr/lib/libpthread.so.0
#8  0x00007ffff3c022d3 in clone () from /usr/lib/libc.so.6
(gdb) 
```

**Comment by itsmattkc** [comment]
Would you be able to provide the project file in question?

**Comment by DaniSeeh** [comment]
Yep. Sending all relevant files in a PM

**Comment by itsmattkc** [comment]
a1f5c85f49ffcbcc25acea8814328028293dbeeb should address this, let me know if it still happens.
