### ISSUE TITLE
[CRASH] Drop some PNGs into bin and then put two on timeline

### ISSUE THREAD

**Issue by DaniSeeh** [sobotka/olive#42]
### Build: 63c1948
Manjaro Gnome 19
Ryzen 1700x
GTX 1070
32GB RAM
NVIDIA 440 Drivers

### Steps to Reproduce
1. Open Olive and Set OCIO Config to nuke-default
2. Create 4k60 Sequence
3. Dropped three PNGs into project bin
4. Drop one PNG onto Timeline, it displayed just fine, no issues.
5. Drop second PNG onto timeline in Track above first one.
6. Clicked on timeline seek bar

```
[daniel@daniel-pc Downloads]$ gdb ./Olive-63c19489-x86_64.AppImage
GNU gdb (GDB) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Olive-63c19489-x86_64.AppImage...
(No debugging symbols found in ./Olive-63c19489-x86_64.AppImage)
(gdb) run
Starting program: /home/daniel/Downloads/Olive-63c19489-x86_64.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Detaching after fork from child process 90998]
process 90994 is executing new program: /tmp/.mount_Olive-2i4BQK/local/bin/olive-editor
warning: Loadable section ".dynstr" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffd55a9700 (LWP 91003)]
[New Thread 0x7fffd1ff2700 (LWP 91004)]
Using Qt version: 5.11.0
[DEBUG] CONFIG: This is a 0.1.x config file, upconvert ((null):0)
[DEBUG]   CONFIG: Finding closest match to "29.97" ((null):0)
[DEBUG]   CONFIG: Closest match was 29.97 ((null):0)
[New Thread 0x7fffd1361700 (LWP 91007)]
[New Thread 0x7fffd0b60700 (LWP 91008)]
[New Thread 0x7fffcbfff700 (LWP 91009)]
[New Thread 0x7fffcb7fe700 (LWP 91010)]
[New Thread 0x7fffcaffd700 (LWP 91011)]
[New Thread 0x7fffca7fc700 (LWP 91012)]
[New Thread 0x7fffc9ffb700 (LWP 91013)]
[New Thread 0x7fffc97fa700 (LWP 91014)]
[New Thread 0x7fffc8ff9700 (LWP 91015)]
[New Thread 0x7fffa7fff700 (LWP 91016)]
[New Thread 0x7fffa77fe700 (LWP 91017)]
[New Thread 0x7fffa6ffd700 (LWP 91018)]
[New Thread 0x7fffa67fc700 (LWP 91019)]
[New Thread 0x7fffa5ffb700 (LWP 91020)]
[New Thread 0x7fffa57fa700 (LWP 91021)]
[New Thread 0x7fffa4ff9700 (LWP 91022)]
[New Thread 0x7fff87fff700 (LWP 91023)]
[New Thread 0x7fff877fe700 (LWP 91024)]
[OpenColorIO Info]: Color management disabled. (Specify the $OCIO environment variable to enable.)
[New Thread 0x7fff77fff700 (LWP 91025)]
[INFO] Setting output audio device to "alsa_output.pci-0000_0c_00.3.analog-stereo" ((null):0)
[WARNING] Invalid params found: 0 0 -1 ((null):0)
[Thread 0x7fffd1361700 (LWP 91007) exited]
[New Thread 0x7fffd1361700 (LWP 91026)]
[Thread 0x7fffd1361700 (LWP 91026) exited]
[New Thread 0x7fffd1361700 (LWP 91027)]
[WARNING] Empty filename passed to function ((null):0)
[Thread 0x7fffd1361700 (LWP 91027) exited]
[WARNING] Invalid params found: 0 0 -1 ((null):0)
[WARNING] Invalid params found: 0 0 -1 ((null):0)
[DEBUG] Cache invalidated between 0 and 0 ((null):0)
[New Thread 0x7fffd1361700 (LWP 91066)]
[New Thread 0x7fff777fe700 (LWP 91067)]
[New Thread 0x7fff76ffd700 (LWP 91068)]
[New Thread 0x7fff767fc700 (LWP 91069)]
[New Thread 0x7fff75ffb700 (LWP 91070)]
[New Thread 0x7fff757fa700 (LWP 91071)]
[New Thread 0x7fff74ff9700 (LWP 91072)]
[New Thread 0x7fff67ffd700 (LWP 91073)]
[New Thread 0x7fff677fc700 (LWP 91074)]
[New Thread 0x7fff66ffb700 (LWP 91075)]
[New Thread 0x7fff667fa700 (LWP 91076)]
[New Thread 0x7fff65ff9700 (LWP 91077)]
[New Thread 0x7fff657f8700 (LWP 91078)]
[New Thread 0x7fff64ff7700 (LWP 91079)]
[New Thread 0x7fff37fff700 (LWP 91080)]
[New Thread 0x7fff377fe700 (LWP 91081)]
[New Thread 0x7fff36ffd700 (LWP 91082)]
[DEBUG] Cache invalidated between 0 and 0 ((null):0)
[New Thread 0x7fff34856700 (LWP 91083)]
[New Thread 0x7fff121c1700 (LWP 91084)]
[New Thread 0x7fff119c0700 (LWP 91085)]
[New Thread 0x7fff111bf700 (LWP 91086)]
[New Thread 0x7fff109be700 (LWP 91087)]
[New Thread 0x7fff03fff700 (LWP 91088)]
[New Thread 0x7fff037fe700 (LWP 91089)]
[New Thread 0x7fff02ffd700 (LWP 91090)]
[New Thread 0x7fff027fc700 (LWP 91091)]
[New Thread 0x7fff01ffb700 (LWP 91092)]
[New Thread 0x7fff017fa700 (LWP 91093)]
[New Thread 0x7fff00ff9700 (LWP 91094)]
[New Thread 0x7ffedffff700 (LWP 91095)]
[New Thread 0x7ffedf7fe700 (LWP 91096)]
[New Thread 0x7ffedeffd700 (LWP 91097)]
[New Thread 0x7ffede7fc700 (LWP 91098)]
[WARNING] Tried to allocate sample buffer with zero sample count ((null):0)
[WARNING] Tried to fill an unallocated sample buffer ((null):0)
[New Thread 0x7ffedca85700 (LWP 91113)]
[Thread 0x7ffedca85700 (LWP 91113) exited]
[DEBUG] Cache invalidated between 0 and 2 ((null):0)
[New Thread 0x7ffedca85700 (LWP 91114)]
[New Thread 0x7ffea3d0f700 (LWP 91115)]
[New Thread 0x7ffea350e700 (LWP 91116)]
[New Thread 0x7ffea2d0d700 (LWP 91117)]
[New Thread 0x7ffea250c700 (LWP 91118)]
[New Thread 0x7ffea1d0b700 (LWP 91119)]
[New Thread 0x7ffea150a700 (LWP 91120)]
[New Thread 0x7ffea0d09700 (LWP 91121)]
[Thread 0x7ffedca85700 (LWP 91114) exited]
[Thread 0x7ffea3d0f700 (LWP 91115) exited]
[Thread 0x7ffea350e700 (LWP 91116) exited]
[Thread 0x7ffea250c700 (LWP 91118) exited]
[Thread 0x7ffea2d0d700 (LWP 91117) exited]
[Thread 0x7ffea0d09700 (LWP 91121) exited]
[Thread 0x7ffea1d0b700 (LWP 91119) exited]
[Thread 0x7ffea150a700 (LWP 91120) exited]
[New Thread 0x7ffea0d09700 (LWP 91122)]
[New Thread 0x7ffea150a700 (LWP 91123)]
[New Thread 0x7ffea1d0b700 (LWP 91124)]
[New Thread 0x7ffea250c700 (LWP 91125)]
[New Thread 0x7ffe9f535700 (LWP 91126)]
[New Thread 0x7ffe9ed34700 (LWP 91127)]
[New Thread 0x7ffe9e533700 (LWP 91128)]
[New Thread 0x7ffe9dd32700 (LWP 91129)]
[DEBUG] Cache invalidated between 0 and 2 ((null):0)
[DEBUG] Cache invalidated between 0 and 2 ((null):0)
[DEBUG] Cache invalidated between 0 and 2 ((null):0)
[New Thread 0x7ffe9d531700 (LWP 91130)]
[New Thread 0x7ffe9cd30700 (LWP 91131)]
[New Thread 0x7ffe7ffff700 (LWP 91132)]
[New Thread 0x7ffe7f7fe700 (LWP 91133)]
[New Thread 0x7ffe7effd700 (LWP 91134)]
[New Thread 0x7ffe7e7fc700 (LWP 91135)]
[New Thread 0x7ffe7dffb700 (LWP 91136)]
[New Thread 0x7ffe7d7fa700 (LWP 91137)]
[Thread 0x7ffe7ffff700 (LWP 91132) exited]
[Thread 0x7ffe7dffb700 (LWP 91136) exited]
[Thread 0x7ffe7effd700 (LWP 91134) exited]
[Thread 0x7ffe7d7fa700 (LWP 91137) exited]
[Thread 0x7ffe9d531700 (LWP 91130) exited]
[Thread 0x7ffe9cd30700 (LWP 91131) exited]
[Thread 0x7ffe7e7fc700 (LWP 91135) exited]
[Thread 0x7ffe7f7fe700 (LWP 91133) exited]
[New Thread 0x7ffe7d7fa700 (LWP 91138)]
[New Thread 0x7ffe7dffb700 (LWP 91139)]
[New Thread 0x7ffe7e7fc700 (LWP 91140)]
[New Thread 0x7ffe7effd700 (LWP 91141)]
[New Thread 0x7ffe9d531700 (LWP 91142)]
[New Thread 0x7ffe9cd30700 (LWP 91143)]
[New Thread 0x7ffe7ffff700 (LWP 91144)]
[New Thread 0x7ffe7f7fe700 (LWP 91145)]
[Thread 0x7ffe7d7fa700 (LWP 91138) exited]
[Thread 0x7ffe7dffb700 (LWP 91139) exited]
[Thread 0x7ffe7effd700 (LWP 91141) exited]
[Thread 0x7ffe7e7fc700 (LWP 91140) exited]
[Thread 0x7ffe9cd30700 (LWP 91143) exited]
[Thread 0x7ffe9d531700 (LWP 91142) exited]
[Thread 0x7ffe7ffff700 (LWP 91144) exited]
[Thread 0x7ffe7f7fe700 (LWP 91145) exited]
[New Thread 0x7ffe7f7fe700 (LWP 91146)]
[New Thread 0x7ffe7ffff700 (LWP 91147)]
[New Thread 0x7ffe9cd30700 (LWP 91148)]
[New Thread 0x7ffe9d531700 (LWP 91149)]
[New Thread 0x7ffe7effd700 (LWP 91150)]
[New Thread 0x7ffe7e7fc700 (LWP 91151)]
[New Thread 0x7ffe7dffb700 (LWP 91152)]
[New Thread 0x7ffe7d7fa700 (LWP 91153)]
[Thread 0x7ffe9cd30700 (LWP 91148) exited]
[Thread 0x7ffe9d531700 (LWP 91149) exited]
[Thread 0x7ffe7e7fc700 (LWP 91151) exited]
[Thread 0x7ffe7dffb700 (LWP 91152) exited]
[Thread 0x7ffe7f7fe700 (LWP 91146) exited]
[Thread 0x7ffe7ffff700 (LWP 91147) exited]
[Thread 0x7ffe7effd700 (LWP 91150) exited]
[Thread 0x7ffe7d7fa700 (LWP 91153) exited]
[DEBUG] Cache invalidated between 0 and 2 ((null):0)
[DEBUG] Cache invalidated between 0 and 4.9 ((null):0)
[New Thread 0x7ffe7d7fa700 (LWP 91154)]
[New Thread 0x7ffe7dffb700 (LWP 91155)]
[New Thread 0x7ffe7e7fc700 (LWP 91156)]
[New Thread 0x7ffe7effd700 (LWP 91157)]
[New Thread 0x7ffe9d531700 (LWP 91158)]
[New Thread 0x7ffe9cd30700 (LWP 91159)]
[New Thread 0x7ffe7ffff700 (LWP 91160)]
[New Thread 0x7ffe7f7fe700 (LWP 91161)]
[Thread 0x7ffe7effd700 (LWP 91157) exited]
[Thread 0x7ffe7dffb700 (LWP 91155) exited]
[Thread 0x7ffe9d531700 (LWP 91158) exited]
[Thread 0x7ffe7d7fa700 (LWP 91154) exited]
[Thread 0x7ffe7f7fe700 (LWP 91161) exited]
[Thread 0x7ffe7e7fc700 (LWP 91156) exited]
[Thread 0x7ffe9cd30700 (LWP 91159) exited]
[Thread 0x7ffe7ffff700 (LWP 91160) exited]
--Type <RET> for more, q to quit, c to continue without paging--<ret>

Thread 1 "AppRun" received signal SIGSEGV, Segmentation fault.
0x0000000000483b7b in olive::rational::operator=(olive::rational const&) ()
(gdb) bt
#0  0x0000000000483b7b in olive::rational::operator=(olive::rational const&) ()
#1  0x000000000057a12d in olive::NodeParamViewKeyframeControl::SetTime(olive::rational const&) ()
#2  0x00000000005771a4 in olive::NodeParamViewItemBody::SetTime(olive::rational const&) ()
#3  0x000000000056fd38 in olive::NodeParamView::UpdateItemTime(long const&) ()
#4  0x000000000058ac28 in olive::TimeBasedWidget::SetTime(long) ()
#5  0x00007ffff2effb56 in QMetaObject::activate(QObject*, int, int, void**) ()
    at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Core.so.5
#6  0x00000000005d7132 in olive::TimeBasedPanel::TimeChanged(long const&) ()
#7  0x00007ffff2effb56 in QMetaObject::activate(QObject*, int, int, void**) ()
    at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Core.so.5
#8  0x00000000005d9e12 in olive::TimeBasedWidget::TimeChanged(long const&) ()
#9  0x00007ffff2effb56 in QMetaObject::activate(QObject*, int, int, void**) ()
    at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Core.so.5
#10 0x00000000005d731f in olive::SeekableWidget::TimeChanged(long) ()
#11 0x00000000005b5cb4 in olive::SeekableWidget::SeekToScreenPoint(int) ()
#12 0x00007ffff398e79f in QWidget::event(QEvent*) ()
    at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Widgets.so.5
#13 0x00007ffff394ec4c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Widgets.so.5
#14 0x00007ffff3956eeb in QApplication::notify(QObject*, QEvent*) ()
    at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Widgets.so.5
--Type <RET> for more, q to quit, c to continue without paging--<ret>
#15 0x00007ffff2ed2ad8 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Core.so.5
#16 0x00007ffff395586f in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
    at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Widgets.so.5
#17 0x00007ffff39a822d in  ()
    at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Widgets.so.5
#18 0x00007ffff39aac3b in  ()
    at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Widgets.so.5
#19 0x00007ffff394ec4c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Widgets.so.5
#20 0x00007ffff39562c7 in QApplication::notify(QObject*, QEvent*) ()
    at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Widgets.so.5
#21 0x00007ffff2ed2ad8 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Core.so.5
#22 0x00007ffff3308ee5 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
    at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Gui.so.5
#23 0x00007ffff330ae55 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
    at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Gui.so.5
#24 0x00007ffff32e343b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
--Type <RET> for more, q to quit, c to continue without paging--<ret>
    at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Gui.so.5
#25 0x00007fffd3e05f4b in  ()
    at /tmp/.mount_Olive-2i4BQK/local/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#26 0x00007ffff2ed0e6a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Core.so.5
#27 0x00007ffff2ed9f74 in QCoreApplication::exec() ()
    at /tmp/.mount_Olive-2i4BQK/local/bin/../lib/libQt5Core.so.5
#28 0x0000000000459749 in main ()
(gdb) 
```

**Comment by DaniSeeh** [comment]
Fixed in f063d47
