### ISSUE TITLE
[CRASH] Crash upon saving

### ISSUE THREAD

**Issue by prokoudine** [sobotka/olive#6]
**Your Setup:**
- Olive version: commit 7a973b9b475db2bb0ded4fb52e6375e3cd6cf16b
- Source: git master
- Operating system: Ubuntu 19.10 64-bit
- CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
- RAM: 8GB
- GPU: Intel HD Graphics 620

**Describe the Bug**
Olive crashes upon saving a project file.

**To Reproduce**

1. Create a new project.
2. Save this project.
3. Restart Olive, reopen the project.
4. Tweak project settings, in particular, OCIO settings.
5. Attempt saving. BOOM.

** Debug Log and/or Crash Report **

```
[FATAL] QThread: Destroyed while thread is still running ((null):0)

Thread 1 "olive-editor" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff40263eb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff4005899 in __GI_abort () at abort.c:79
#2  0x00007ffff45afa99 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff45b0296 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff45e6abd in QThread::~QThread() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff47dbcd4 in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff51c1a86 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff51cae00 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff47afa9a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff47b2718 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff48080a7 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff2ee784d in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff2ee7ad0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff2ee7b73 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff48076a5 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff47ae63b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff47b63a6 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00005555555d1293 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /home/alex/soft/video/olive/olive-2020-01-19/app/main.cpp:91
```

**Comment by itsmattkc** [comment]
I haven't been able to recreate this, and judging by the nature of the error I'm going to assume this has been corrected by later advancements. If it still occurs, let me know.
