### ISSUE TITLE
[CRASH] Crash upon tweaking OCIO settings in the exporting dialog

### ISSUE THREAD

**Issue by prokoudine** [sobotka/olive#7]
**Your Setup:**
- Olive version: commit 7a973b9b475db2bb0ded4fb52e6375e3cd6cf16b
- Source: git master
- Operating system: Ubuntu 19.10 64-bit
- CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
- RAM: 8GB
- GPU: Intel HD Graphics 620

**Describe the Bug**
Olive crashes upon tweaking OCIO settings in the exporting dialog.

**To Reproduce**

1. Create a new project, create new sequence etc.
2. Go to File > Export...
3. Start clicking drop-down lists in the OCIO section.
4. BOOM.

**Debug Log and/or Crash Report**

```
Thread 40 "QThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff87bff700 (LWP 5460)]
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x000055555569273e in RenderWorker::GenerateDatabase(Node const*, TimeRange const&) (this=0x555557be7ce0, node=0x555557645d50, range=...)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/renderworker.cpp:125
#2  0x0000555555692e33 in RenderWorker::ProcessNode(NodeDependency const&) (this=0x555557be7ce0, dep=...)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/renderworker.cpp:92
#3  0x0000555555692fb2 in RenderWorker::ProcessInput(NodeInput const*, TimeRange const&) (this=0x555557be7ce0, input=0x555558440d70, range=...)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/renderworker.cpp:107
#4  0x0000555555692770 in RenderWorker::GenerateDatabase(Node const*, TimeRange const&) (this=0x555557be7ce0, node=0x55555843f530, range=...)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/renderworker.cpp:129
#5  0x0000555555692e33 in RenderWorker::ProcessNode(NodeDependency const&) (this=this@entry=0x555557be7ce0, dep=...)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/renderworker.cpp:92
#6  0x00005555556a5d44 in VideoRenderWorker::RenderBlock(TrackOutput const*, TimeRange const&)
    (this=this@entry=0x555557be7ce0, track=track@entry=0x5555577d9fb0, range=...)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/videorenderworker.cpp:244
#7  0x0000555555692de7 in RenderWorker::ProcessNode(NodeDependency const&) (this=this@entry=0x555557be7ce0, dep=...)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/renderworker.cpp:86
#8  0x00005555556a71f5 in VideoRenderWorker::RenderInternal(NodeDependency const&, long long const&)
    (this=0x555557be7ce0, path=..., job_time=@0x7fff87bfd368: 1579472524962)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/videorenderworker.cpp:60
#9  0x0000555555693154 in RenderWorker::Render(NodeDependency, long long) (this=0x555557be7ce0, path=..., job_time=<optimized out>)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/node/value.h:24
#10 0x0000555555719138 in RenderWorker::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)
    (_o=0x555557be7ce0, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at /home/alex/soft/video/olive/olive-2020-01-19/build/app/olive-editor_autogen/5EZTQ7W44Y/moc_renderworker.cpp:91
#11 0x00007ffff47dbeba in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff51c1a86 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff51cae00 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff47afa9a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff47b2718 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff48080a7 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff2ee784d in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff2ee7ad0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff2ee7b73 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff48076a5 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff47ae63b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff45e7a75 in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff45e8cc2 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff3c20669 in start_thread (arg=<optimized out>) at pthread_create.c:479
#25 0x00007ffff4102323 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by itsmattkc** [comment]
I think this was fixed in a recent commit, let me know if it still happens in latest
