### ISSUE TITLE
[CRASH] Crash when cancelling the Export dialog

### ISSUE THREAD

**Issue by prokoudine** [sobotka/olive#8]
**Platform**

- Olive version: commit 7a973b9b475db2bb0ded4fb52e6375e3cd6cf16b
- Source: git master
- Operating system: Ubuntu 19.10 64-bit
- CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
- RAM: 8GB
- GPU: Intel HD Graphics 620

**Summary**

1. Go to File > Export
2. Click around in OCIO settings
3. Click Cancel

**Additional Information / Output**

```
Thread 1 "olive-editor" received signal SIGSEGV, Segmentation fault.
0x00005555556766b5 in OpenGLColorProcessor::~OpenGLColorProcessor (this=0x7fff44a957c0, __in_chrg=<optimized out>)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/opengl/openglcolorprocessor.cpp:53
53	    context_->functions()->glDeleteTextures(1, &ocio_lut_);
(gdb) bt
#0  0x00005555556766b5 in OpenGLColorProcessor::~OpenGLColorProcessor() (this=0x7fff44a957c0, __in_chrg=<optimized out>)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/opengl/openglcolorprocessor.cpp:53
#1  0x00005555555d9b08 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() (this=0x7fff44a957b0)
    at /usr/include/c++/9/bits/shared_ptr_base.h:148
#2  0x00005555555d9b08 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() (this=0x7fff44a957b0)
    at /usr/include/c++/9/bits/shared_ptr_base.h:148
#3  0x000055555567f79c in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() (this=0x7fff44a7fe28, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#4  0x000055555567f79c in std::__shared_ptr<ColorProcessor, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() (this=0x7fff44a7fe20, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#5  0x000055555567f79c in std::shared_ptr<ColorProcessor>::~shared_ptr() (this=0x7fff44a7fe20, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr.h:103
#6  0x000055555567f79c in QMapNodeBase::callDestructorIfNecessary<std::shared_ptr<ColorProcessor> >(std::shared_ptr<ColorProcessor>&)
    (t=std::shared_ptr<ColorProcessor> (expired, weak count 1) = {...}) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h:103
#7  0x000055555567f79c in QMapNode<QString, std::shared_ptr<ColorProcessor> >::destroySubTree() (this=0x7fff44a7fe00)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h:128
#8  0x000055555567f79c in QMapData<QString, std::shared_ptr<ColorProcessor> >::destroy() (this=0x7fff44a9fed0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h:248
#9  0x000055555567f79c in QMap<QString, std::shared_ptr<ColorProcessor> >::~QMap() (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h:339
#10 0x000055555567f79c in RenderCache<QString, std::shared_ptr<ColorProcessor> >::~RenderCache() (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/opengl/../rendercache.h:8
#11 0x000055555567f79c in VideoRenderWorker::~VideoRenderWorker() (this=0x555556a15bb0, __in_chrg=<optimized out>)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/opengl/../videorenderworker.h:12
#12 0x000055555567f79c in OpenGLWorker::~OpenGLWorker() (this=0x555556a15bb0, __in_chrg=<optimized out>)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/opengl/openglworker.cpp:23
#13 0x0000555555681c6d in OpenGLWorker::~OpenGLWorker() (this=0x555556a15bb0, __in_chrg=<optimized out>)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/opengl/openglworker.cpp:23
#14 0x000055555568d156 in RenderBackend::Close() (this=0x555555e0e110) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h:61
#15 0x000055555568d156 in RenderBackend::Close() (this=this@entry=0x555555e0e110)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/renderbackend.cpp:45
#16 0x000055555566f668 in OpenGLBackend::~OpenGLBackend() (this=0x555555e0e110, __in_chrg=<optimized out>)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/opengl/openglbackend.cpp:16
#17 0x0000555555671bad in OpenGLBackend::~OpenGLBackend() (this=0x555555e0e110, __in_chrg=<optimized out>)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/render/backend/opengl/openglbackend.cpp:14
#18 0x00007ffff47d917e in QObjectPrivate::deleteChildren() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff51ff919 in QWidget::~QWidget() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x000055555572d285 in ViewerWidget::~ViewerWidget() (this=0x555556a83450, __in_chrg=<optimized out>)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/widget/viewer/viewer.h:44
#21 0x000055555572d285 in ViewerWidget::~ViewerWidget() (this=0x555556a83450, __in_chrg=<optimized out>)
    at /home/alex/soft/video/olive/olive-2020-01-19/app/widget/viewer/viewer.h:44
#22 0x00007ffff47d917e in QObjectPrivate::deleteChildren() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff51ff919 in QWidget::~QWidget() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff51ffb0d in QWidget::~QWidget() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff47d917e in QObjectPrivate::deleteChildren() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff51ff919 in QWidget::~QWidget() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff537461d in QSplitter::~QSplitter() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff47d917e in QObjectPrivate::deleteChildren() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff51ff919 in QWidget::~QWidget() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00005555555d82e6 in ExportDialog::~ExportDialog() (this=0x7fffffffcc20, __in_chrg=<optimized out>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:75
#31 0x00005555555d82e6 in Core::DialogExportShow() (this=<optimized out>) at /home/alex/soft/video/olive/olive-2020-01-19/app/core.cpp:258
#32 0x000055555571b166 in Core::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)
    (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at /home/alex/soft/video/olive/olive-2020-01-19/build/app/olive-editor_autogen/EWIEGA46WW/moc_core.cpp:155
#33 0x00007ffff47db468 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff51bb406 in QAction::triggered(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007ffff51bdac2 in QAction::activate(QAction::ActionEvent) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007ffff5343362 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007ffff534aaae in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007ffff534bad2 in QMenu::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007ffff520404e in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#40 0x00007ffff534e0cb in QMenu::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#41 0x00007ffff51c1a86 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#42 0x00007ffff51cb053 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#43 0x00007ffff47afa9a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#44 0x00007ffff51ca157 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#45 0x00007ffff5220ad4 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#46 0x00007ffff5222fdc in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#47 0x00007ffff51c1a86 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#48 0x00007ffff51cae00 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#49 0x00007ffff47afa9a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#50 0x00007ffff4b97d73 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#51 0x00007ffff4b995fb in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#52 0x00007ffff4b7326b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#53 0x00007fffe057028e in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#54 0x00007ffff2ee784d in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#55 0x00007ffff2ee7ad0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#56 0x00007ffff2ee7b73 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#57 0x00007ffff48076a5 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#58 0x00007ffff47ae63b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#59 0x00007ffff47b63a6 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#60 0x00005555555d1293 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /home/alex/soft/video/olive/olive-2020-01-19/app/main.cpp:91
```

**Comment by itsmattkc** [comment]
Should be fixed as of 24f7eeb210f91472c70fcd1ff29ee1fb473cc7e8
